# random variable is a numeric outcome generated by an event.
# for example in the beads in urn
urn<- rep(c("blue", "red"), times = c(3, 2))

# generate 1 if bead is blue, else 0
ifelse(sample(urn,1) == 'blue', 1, 0)

# sampling models (random)
# example of roulette game
color <- rep(c('Black', 'Green', 'Red'), c(18, 2, 18))

# 1000 people are playing so 1000 outcomes
n <- 1000
X <- sample(ifelse(color == 'Red', -1, 1), n, replace = TRUE)
X[1:5]

# We know the probability as 18/38 (losing), 20/38 (winning)
X <- sample(c(-1, 1), n, replace = TRUE,
            prob = c(18/38, 20/38))
X[1:5] # this is called modeling of random behaviour of roulette.

# we can define cumulative distribution using monte-carlo simulation.
# lets run this code 10000 times
B <- 10000
winnings <- function(n){
    X <- sample(c(-1, 1), n, replace = TRUE,
                prob = c(18/38, 20/38))
    sum(X)
}
S <- replicate(B, winnings(n))

# How often was sum less than 0
mean(S < 0) # 4.5% of time casino lost money.

# generating new data and plotting it against generated data to verify
# normal distribution
library(tidyverse)

# generate 100 data within the range of S
s <- seq(min(S), max(S), length=100)

# generate normal density for s
normal_density <- data.frame(s=s, f = dnorm(s, mean(S), sd(S)))

# make dataframe of S for histogram
data.frame(S = S) %>% ggplot(aes(S, ..density..)) +
    geom_histogram(color='black', binwidth = 10) +
    ylab("Probability") +
    geom_line(mapping = aes(s,f), data = normal_density, color='blue')

